<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\AluguelFilmeModel;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tbalugueis', function (Blueprint $table) {
            $table->id('id_aluguel');
            $table->unsignedBigInteger('id_user');
            $table->unsignedBigInteger('id_filme');
            $table->date('validade_aluguel');
            $table->float('valor_filme')->length(4,2);
            $table->boolean('devolvido')->default(false);
            $table->foreign('id_user')
            ->references('id')->on('users')->onDelete('cascade');
            $table->foreign('id_filme')
            ->references('id_filme')->on('tbfilmes')->onDelete('cascade');
        });

        $data = array(
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],                        [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],         
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],                        [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],         
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],                        [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],         
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],                        [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-01-31',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 2,
                'id_filme' => 2,
                'validade_aluguel' => '2022-02-28',
                'valor_filme' => 89.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-13',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-04-24',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-05-03',
                'valor_filme' => 92.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-06-09',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-12-04',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-01-22',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 3,
                'validade_aluguel' => '2022-02-12',
                'valor_filme' => 97.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-03-07',
                'valor_filme' => 94.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 5,
                'validade_aluguel' => '2022-04-23',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-05-26',
                'valor_filme' => 99.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-06-30',
                'valor_filme' => 98.00,
                'devolvido' => 1,
            ],            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-07-11',
                'valor_filme' => 91.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 6,
                'validade_aluguel' => '2022-08-31',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-09-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            
            [
                'id_user' => 1,
                'id_filme' => 2,
                'validade_aluguel' => '2022-10-22',
                'valor_filme' => 95.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 1,
                'validade_aluguel' => '2022-11-01',
                'valor_filme' => 93.00,
                'devolvido' => 1,
            ],
            [
                'id_user' => 1,
                'id_filme' => 4,
                'validade_aluguel' => '2022-12-26',
                'valor_filme' => 96.00,
                'devolvido' => 1,
            ],            

            
        
        );
        foreach ($data as $d){
            $tbalugueis = new AluguelFilmeModel();
            $tbalugueis->id_user =$d['id_user'];
            $tbalugueis->id_filme =$d['id_filme'];
            $tbalugueis->validade_aluguel =$d['validade_aluguel'];
            $tbalugueis->valor_filme =$d['valor_filme'];
            $tbalugueis->devolvido = $d['devolvido'];
            $tbalugueis->save();
        }

    }
    /**
     * 
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tbalugueis');
    }
};
